<?php

namespace Database\Seeders;

use App\Models\Rawafed\Permission;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [
            [
                'slug'=>'profile',
                'name_ar'=>__('dashboard.controlProfile',[],'ar'),
                'name_en'=>__('dashboard.controlProfile',[],'en')
            ],
            [
                'slug'=>'my-favourite',
                'name_ar'=>__('dashboard.MyFavourite',[],'ar'),
                'name_en'=>__('dashboard.MyFavourite',[],'en')
            ],
            [
                'slug'=>'control-delete',
                'name_ar'=>__('dashboard.controlDelete',[],'ar'),
                'name_en'=>__('dashboard.controlDelete',[],'en'),
            ],
            [
                'slug'=>'information',
                'name_ar'=>__('dashboard.controlInformation',[],'ar'),
                'name_en'=>__('dashboard.controlInformation',[],'en'),
            ],
            [
                'slug'=>'social-media',
                'name_ar'=>__('dashboard.controlSocialMedia',[],'ar'),
                'name_en'=>__('dashboard.controlSocialMedia',[],'en'),
            ],
            [
                'slug'=>'geographic-places',
                'name_ar'=>__('dashboard.controlGeographicPlaces',[],'ar'),
                'name_en'=>__('dashboard.controlGeographicPlaces',[],'en'),
            ],
            [
                'slug'=>'directorates',
                'name_ar'=>__('dashboard.controlDirectorates',[],'ar'),
                'name_en'=>__('dashboard.controlDirectorates',[],'en'),
            ],
            [
                'slug'=>'schools',
                'name_ar'=>__('dashboard.controlSchools',[],'ar'),
                'name_en'=>__('dashboard.controlSchools',[],'en'),
            ],
            [
                'slug'=>'levels',
                'name_ar'=>__('dashboard.controlLevels',[],'ar'),
                'name_en'=>__('dashboard.controlLevels',[],'en'),
            ],
            [
                'slug'=>'grades',
                'name_ar'=>__('dashboard.controlGrades',[],'ar'),
                'name_en'=>__('dashboard.controlGrades',[],'en'),
            ],
            [
                'slug'=>'subjects',
                'name_ar'=>__('dashboard.controlSubjects',[],'ar'),
                'name_en'=>__('dashboard.controlSubjects',[],'en'),
            ],
            [
                'slug'=>'semesters',
                'name_ar'=>__('dashboard.controlSemesters',[],'ar'),
                'name_en'=>__('dashboard.controlSemesters',[],'en'),
            ],
            [
                'slug'=>'unit-categories',
                'name_ar'=>__('dashboard.controlUnitCategories',[],'ar'),
                'name_en'=>__('dashboard.controlUnitCategories',[],'en'),
            ],
            [
                'slug'=>'units',
                'name_ar'=>__('dashboard.controlUnits',[],'ar'),
                'name_en'=>__('dashboard.controlUnits',[],'en'),
            ],
            [
                'slug'=>'video-types',
                'name_ar'=>__('dashboard.controlVideoTypes',[],'ar'),
                'name_en'=>__('dashboard.controlVideoTypes',[],'en'),
            ],
            [
                'slug'=>'lessons',
                'name_ar'=>__('dashboard.controlLessons',[],'ar'),
                'name_en'=>__('dashboard.controlLessons',[],'en'),
            ],
            [
                'slug'=>'books',
                'name_ar'=>__('dashboard.controlBooks',[],'ar'),
                'name_en'=>__('dashboard.controlBooks',[],'en'),
            ],
            [
                'slug'=>'interactive-books',
                'name_ar'=>__('dashboard.controlInteractiveBooks',[],'ar'),
                'name_en'=>__('dashboard.controlInteractiveBooks',[],'en'),
            ],
            [
                'slug'=>'status',
                'name_ar'=>__('dashboard.controlStatus',[],'ar'),
                'name_en'=>__('dashboard.controlStatus',[],'en'),
            ],
            [
                'slug'=>'file-categories',
                'name_ar'=>__('dashboard.controlFileCategories',[],'ar'),
                'name_en'=>__('dashboard.controlFileCategories',[],'en'),
            ],
            [
                'slug'=>'file-materials',
                'name_ar'=>__('dashboard.controlFileMaterials',[],'ar'),
                'name_en'=>__('dashboard.controlFileMaterials',[],'en'),
            ],
            [
                'slug'=>'roles',
                'name_ar'=>__('dashboard.controlRoles',[],'ar'),
                'name_en'=>__('dashboard.controlRoles',[],'en'),
            ],
            [
                'slug'=>'users',
                'name_ar'=>__('dashboard.controlUsers',[],'ar'),
                'name_en'=>__('dashboard.controlUsers',[],'en'),
            ],
            [
                'slug'=>'permissions',
                'name_ar'=>__('dashboard.controlPermissions',[],'ar'),
                'name_en'=>__('dashboard.controlPermissions',[],'en'),
            ],
            [
                'slug'=>'file-material-settings',
                'name_ar'=>__('dashboard.controlFileMaterialSettings',[],'ar'),
                'name_en'=>__('dashboard.controlFileMaterialSettings',[],'en'),
            ],
            [
                'slug'=>'add-file-material',
                'name_ar'=>__('dashboard.addFileMaterial',[],'ar'),
                'name_en'=>__('dashboard.addFileMaterial',[],'en'),
            ],
            [
                'slug'=>'show-file-material',
                'name_ar'=>__('dashboard.showFileMaterial',[],'ar'),
                'name_en'=>__('dashboard.showFileMaterial',[],'en'),
            ],
            [
                'slug'=>'edit-file-material',
                'name_ar'=>__('dashboard.editFileMaterial',[],'ar'),
                'name_en'=>__('dashboard.editFileMaterial',[],'en'),
            ],
            [
                'slug'=>'trash-file-material',
                'name_ar'=>__('dashboard.trashFileMaterial',[],'ar'),
                'name_en'=>__('dashboard.trashFileMaterial',[],'en'),
            ],
            [
                'slug'=>'show-trash-file-material',
                'name_ar'=>__('dashboard.showTrashedFileMaterial',[],'ar'),
                'name_en'=>__('dashboard.showTrashedFileMaterial',[],'en'),
            ],
            [
                'slug'=>'restore-trash-file-material',
                'name_ar'=>__('dashboard.restoreTrashedFileMaterial',[],'ar'),
                'name_en'=>__('dashboard.restoreTrashedFileMaterial',[],'en'),
            ],
            [
                'slug'=>'destroy-file-material',
                'name_ar'=>__('dashboard.destroyFileMaterial',[],'ar'),
                'name_en'=>__('dashboard.destroyFileMaterial',[],'en'),
            ],
            [
                'slug'=>'confirm-file-material',
                'name_ar'=>__('dashboard.confirmFileMaterial',[],'ar'),
                'name_en'=>__('dashboard.confirmFileMaterial',[],'en'),
            ],
            [
                'slug'=>'show-all-files',
                'name_ar'=>__('dashboard.showAllFiles',[],'ar'),
                'name_en'=>__('dashboard.showAllFiles',[],'en'),
            ],
            [
                'slug'=>'show-subject-committee-files',
                'name_ar'=>__('dashboard.subjectCommittee',[],'ar'),
                'name_en'=>__('dashboard.subjectCommittee',[],'en'),
            ],
            [
                'slug'=>'show-ministry-committee-files',
                'name_ar'=>__('dashboard.ministryCommittee',[],'ar'),
                'name_en'=>__('dashboard.ministryCommittee',[],'en'),
            ],
            [
                'slug'=>'supervisor-permission',
                'name_ar'=>__('dashboard.supervisor-permission',[],'ar'),
                'name_en'=>__('dashboard.supervisor-permission',[],'en'),
            ],
            [
                'slug'=>'user-messages',
                'name_ar'=>__('dashboard.controlUserMessages',[],'ar'),
                'name_en'=>__('dashboard.controlUserMessages',[],'en'),
            ],
            [
                'slug'=>'site-statistics',
                'name_ar'=>__('dashboard.controlSiteStatistics',[],'ar'),
                'name_en'=>__('dashboard.controlSiteStatistics',[],'en'),
            ],

            /**************************************** ECard Permissions ****************************************/

            [
                'slug'=>'e-cards',
                'name_ar'=>__('dashboard.ECards',[],'ar'),
                'name_en'=>__('dashboard.ECards',[],'en'),
            ],
            [
                'slug'=>'show-trashed-ECard',
                'name_ar'=>__('dashboard.showTrashedECard',[],'ar'),
                'name_en'=>__('dashboard.showTrashedECard',[],'en'),
            ],
            [
                'slug'=>'restore-ECard',
                'name_ar'=>__('dashboard.restoreECard',[],'ar'),
                'name_en'=>__('dashboard.restoreECard',[],'en'),
            ],
            [
                'slug'=>'destroy-ECard',
                'name_ar'=>__('dashboard.destroyECard',[],'ar'),
                'name_en'=>__('dashboard.destroyECard',[],'en'),
            ],
            [
                'slug'=>'resource-types',
                'name_ar'=>__('dashboard.resource-types',[],'ar'),
                'name_en'=>__('dashboard.resource-types',[],'en'),
            ],
            [
                'slug'=>'videoLessons',
                'name_ar'=>__('dashboard.videoLessons',[],'ar'),
                'name_en'=>__('dashboard.videoLessons',[],'en'),
            ],
            [
                'slug'=>'control-ministry-exams',
                'name_ar'=>__('dashboard.ministry-exams',[],'ar'),
                'name_en'=>__('dashboard.ministry-exams',[],'en'),
            ],
            [
                'slug'=>'collective-cards',
                'name_ar'=>__('dashboard.collectiveCards',[],'ar'),
                'name_en'=>__('dashboard.collectiveCards',[],'en'),
            ],
            [
                'slug'=>'static-page',
                'name_ar'=>__('dashboard.controlStaticPage',[],'ar'),
                'name_en'=>__('dashboard.controlStaticPage',[],'en'),
            ],


            /************************************** laboratories *******************************************/
            [
                'slug'=>'laboratories',
                'name_ar'=>__('dashboard.controlLaboratories',[],'ar'),
                'name_en'=>__('dashboard.controlLaboratories',[],'en'),
            ],
            [
                'slug'=>'news',
                'name_ar'=>__('dashboard.controlNews',[],'ar'),
                'name_en'=>__('dashboard.controlNews',[],'en'),
            ],
            [
                'slug'=>'publish-new',
                'name_ar'=>__('dashboard.publishNews',[],'ar'),
                'name_en'=>__('dashboard.publishNews',[],'en')
            ],
            [
                'slug'=>'return-new',
                'name_ar'=>__('dashboard.returnNews',[],'ar'),
                'name_en'=>__('dashboard.returnNews',[],'en')
            ],
            [
                'slug'=>'lab-categories',
                'name_ar'=>__('dashboard.controlLabCategories',[],'ar'),
                'name_en'=>__('dashboard.controlLabCategories',[],'en')
            ],
            [
                'slug'=>'concepts',
                'name_ar'=>__('dashboard.controlConcepts',[],'ar'),
                'name_en'=>__('dashboard.controlConcepts',[],'en')
            ],
            [
                'slug'=>'lab-content',
                'name_ar'=>__('dashboard.controlLibraryContents',[],'ar'),
                'name_en'=>__('dashboard.controlLibraryContents',[],'en')
            ],
            [
                'slug'=>'lab-supervision',
                'name_ar'=>__('dashboard.controlLabSupervision',[],'ar'),
                'name_en'=>__('dashboard.controlLabSupervision',[],'en')
            ],
            /************************************** TV *******************************************/
            [
                'slug'=>'rawafed-tv',
                'name_ar'=>__('dashboard.controlTv',[],'ar'),
                'name_en'=>__('dashboard.controlTv',[],'en'),
            ],
            [
                'slug'=>'programs',
                'name_ar'=>__('dashboard.controlPrograms',[],'ar'),
                'name_en'=>__('dashboard.controlPrograms',[],'en'),
            ],
            [
                'slug'=>'episodes',
                'name_ar'=>__('dashboard.controlEpisodes',[],'ar'),
                'name_en'=>__('dashboard.controlEpisodes',[],'en')
            ],
            [
                'slug'=>'broadcast-times',
                'name_ar'=>__('dashboard.controlBroadcast-times',[],'ar'),
                'name_en'=>__('dashboard.controlBroadcast-times',[],'en')
            ],
            [
                'slug'=>'broadcasts',
                'name_ar'=>__('dashboard.controlBroadcasts',[],'ar'),
                'name_en'=>__('dashboard.controlBroadcasts',[],'en')
            ],
            [
                'slug'=>'contacts',
                'name_ar'=>__('dashboard.controlContacts',[],'ar'),
                'name_en'=>__('dashboard.controlContacts',[],'en')
            ],
            [
                'slug'=>'congratulations',
                'name_ar'=>__('dashboard.controlCongratulations',[],'ar'),
                'name_en'=>__('dashboard.controlCongratulations',[],'en')
            ],
        ];
        Permission::insert($permissions);
    }
}
